apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: glpi-phpmyadmin
  name: glpi-phpmyadmin
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: glpi-phpmyadmin
    spec:
      containers:
      - env:
        - name: PMA_HOST
          value: glpi-dbmysql
        - name: PMA_PASSWORD
          value: docker
        - name: PMA_USER
          value: root
        image: phpmyadmin/phpmyadmin
        name: glpi-phpmyadmin
        ports:
        - containerPort: 80
        resources: {}
      hostname: glpiphpmyadmin
      restartPolicy: Always
status: {}
